#!/bin/bash

#echo "Deleting ENN-ENV"
#eval "bash"
#eval "yes | conda deactivate"
#eval "yes | conda env remove -n enn-env"

echo "Creating new ENN-ENV"
eval "yes | conda create -n enn-env python=3.11"
eval "conda activate enn-env"

echo "Installing packages"
eval "yes | conda config --add channels conda-forge"
eval "yes | conda config --set channel_priority strict"
eval "yes | conda install pip"
eval "yes | conda install pandas"
eval "yes | conda install matplotlib"
eval "yes | conda install jupyter"
eval "yes | conda install pytorch torchvision torchaudio cpuonly -c pytorch"
eval "yes | conda install --upgrade pip setuptools"
eval "yes | conda install numpy"
eval "yes | conda install pandas"
eval "yes | conda install plotnine"
eval "yes | conda install chex"
eval "yes | conda install dm-haiku"
eval "yes | conda install jax"
eval "yes | conda install optax"
eval "yes | conda install tensorflow"
eval "yes | conda install tensorflow-datasets"
eval "yes | conda install scipy=1.12.0"
#eval "git clone https://github.com/deepmind/enn.git"
#eval "pip -m install -q enn/"

#eval "python3 -m venv enn"
#eval "source enn/bin/activate"
#eval "pip install --upgrade pip setuptools"
#eval "pip install numpy"
#eval "pip install pandas"
#eval "pip install plotnine"
#eval "pip install chex"
#eval "pip install dm-haiku"
#eval "pip install jax"
#eval "pip install optax"
#eval "pip install tensorflow"
#eval "pip install tensorflow-datasets"
#eval "git clone https://github.com/deepmind/enn.git"
#eval "pip install -q enn/"

echo "done"